### ISSUE TITLE
minify variable name

### ISSUE THREAD

**Issue by the-liquid-metal** [tedious/JShrink#54]
Do you have any plan for minifying variable name?

**Comment by dugwood** [comment]
Maybe you can use the code from https://github.com/tchwork/jsqueeze

**Comment by 4DallasC** [comment]
Hello @dugwood,

JSqueeze looks like it only renames function parameters and locally defined var variables, and not locally defined let variables within the function. But otherwise it performs better than JShrink.

Thanks,

**Comment by dugwood** [comment]
Locally defined variables are the most important I think. Badly defined variables (global that should be local) are to stay as is.
I chose JShrink for its volume of downloads on packagist.

Sadly you can't use both at the same time, because both scripts need clean initial code. But even without variable minifying, I won't go back to YUI, as JShrink is blazing fast.

Maybe we can manage to create a simplified code for variables declared with `var`, and only these? That would be a good start :-)

**Comment by tedivm** [comment]
I have no plans on doing this- it would require a lot more effort to do properly, as there would need to be proper tokenization/parsing to understand scope and deal with things properly. It would be a complete rearchitecture, and honestly if that's what you need there are already better tools out there for it (just not in php).
