### ISSUE TITLE
JShrink never finishes or is very slow when using PHP 8

### ISSUE THREAD

**Issue by Findus23** [tedious/JShrink#96]
Originally reported in https://github.com/matomo-org/matomo/issues/16707

Minimal testcase (using https://code.jquery.com/jquery-3.5.1.js):
```php
<?php
ini_set('max_execution_time', 30);
include('vendor/autoload.php');
$js = file_get_contents("jquery-3.5.1.js");
$minifiedCode = \JShrink\Minifier::minify($js);
echo $minifiedCode;
```

takes 30 seconds to run when calling with `php8 script.php` (but weirdly enough outputs a minified js which is only missing a `;` at the end).

using PHP 8.0.0RC2 (but the same issue also occurs in Matomo when using RC3)

**Comment by sgiehl** [comment]
@tedivm This was actually indirectly fixed by https://github.com/tedious/JShrink/commit/ca8970bd84e78eabaf0daa30eb591161b4d71859.
The current release always hangs on PHP 8-rc*, as the return value of `substr` changed for an index greater than the length of the string. Might be a bug in PHP maybe.

`substr('test', 5, 1)`  returns `false` on PHP 7, but an empty string on PHP 8-rc*.

Would you mind releasing a new version?

**Comment by Findus23** [comment]
This seems to be an intentional change in PHP as seen in 
https://stackoverflow.com/questions/64855213/substr-returns-an-empty-string-when-string-is-less-than-start-characters-long-in/64855386#64855386
and 
https://github.com/php/php-src/pull/6182

**Comment by klausi** [comment]
This was released, issue can be closed.
